import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.scss'
import { ThemeProvider } from '../providers'
import { i18n } from '@/i18n-config'

const sansPro = localFont({
	src: [
		{
			path: '../../assets/fonts/SourceSansPro-Regular.woff2',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../../assets/fonts/SourceSansPro-SemiBold.woff2',
			weight: '600',
			style: 'normal',
		},
	],
	variable: '--source-sans',
})
const merriWeather = localFont({
	src: '../../assets/fonts/Merriweather-Bold.woff2',
	weight: '700',
	style: 'normal',
	variable: '--merriweather',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode
	params: { lang: string }
}) {
	return (
		<html lang={params.lang}>
			<body className={`${merriWeather.variable} ${sansPro.variable}`}>
				<ThemeProvider>{children}</ThemeProvider>
			</body>
		</html>
	)
}

export async function generateStaticParams() {
	return i18n.locales.map((locale) => ({ lang: locale }))
}
